# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0


##### SONARCLOUD #####


- task: SonarCloudPrepare@2
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'SonarCloud_Token'
    organization: 'romi29396'
    scannerMode: 'MSBuild'
    projectKey: 'romi29396_ CPlusPlus'
    projectName: 'CPlusPlus'

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

